spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://139.196.190.46:3306/baby?useUnicode=true&characterEncoding=utf-8
    username: root
    password: '{cipher}43d6932c38343e3338f5ea1a1b9f58941760103059f610b80da8c97a83c421c9'
    # Hikari 连接池配置
    hikari:
      minimum-idle: 3  # 最小空闲连接数量
      maximum-pool-size: 5  # 连接池最大连接数，默认是10
      max-lifetime: 1800000  # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-test-query: SELECT 1
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
