GET http://localhost:8801/v1/licenses/organization/1
Accept: application/json

###
GET http://localhost:8801/v1/licensesAndOrganization/4/feign
Accept: application/json

###
GET http://localhost:8801/v1/licensesAndOrganization/2/rest
Accept: application/json

###
GET http://localhost:8801/v1/licensesAndOrganization/3/discovery
Accept: application/json

###
GET http://localhost:8802/v1/organization/1
Accept: application/json

###
GET http://localhost:8801/v1/licenses/1
Accept: application/json

###
GET http://localhost:8000/licensingservice/prod
Accept: application/json

